// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;
pragma experimental ABIEncoderV2;

interface IVeSeaProfiles {
    function getProfile(address profileAddress)
        external
        view
        returns (VeSeaProfiles.Profile memory);
}

interface VeSeaProfiles {
    struct Profile {
        address profileAddress;
        string name;
        bool blacklisted;
        bool verified;
        bool payWithVSea;
        uint256 profileTypeId;
        address pfpContract;
        uint256 pfpTokenId;
        uint256 blockCreated;
    }
}
